// <auto-generated />
namespace ToDoListTeldat.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class item_updated_again : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(item_updated_again));
        
        string IMigrationMetadata.Id
        {
            get { return "202103172111372_item_updated_again"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
